version: '3'

services:
  eleventy:
    image: timbru31/node-alpine-git
    volumes:
      - ${PWD}:/app
    working_dir: /app
    command: ["npx", "-p", "@11ty/eleventy", "eleventy", "--watch", "--serve"]
    ports:
      - 8080:8080
    
